
# Questionnaires


Data from questionnaires and instructions are somewhat similar to the data collected from cognitive tasks.

There are however differences in how certain elements are typically named in different contexts. 

For example, in cognitive psychology it is common to name the information presented to subjects and that they have to process to make a decision or provide a response as stimulus. However, in questionnaires it is more common to call this information a "question" or "item". When presenting information about what the subject is expected to do (where the required response might be press the button Next when you're ready) we may call that information "instructions" or "message". 

It is true that by keeping domain specific terminology it is easier to understand what a specific terms refers to. However, is also common to mix these different kinds of data. For example, a study may interleave instructions, trials from cognitive test and questions. A common data model makes it possible to describe all the related behavioral data in a consistent manner, preserving the order of events and the meaning of the variables.

This is the design that we've adopted in the behaverse data model.




Many of the variables that are relevant for describing data from cognitive tests are also relevant for describing data from questionnaires.

There are however some differences:
in questionnaires, people rarely use the term stimulus. Instead they use the term "question" or "item" (althougth the latter term is somewhat abmiguous)

There is also the idea of score that is common in questionnaires but less in cognitive tests.


Messages (an in particular instructions) are quite similar to questionnaires.

