## Naming people

There are three issues related to naming people in a dataset; they concern how to name the "entity" (e.g., "participant" versus "subject"), which suffixes to use (e.g., "\_id" versus "\_index") and what format to use for its values (e.g., an integer or a string). We will go over each of this in turn and justify our choices.

### Naming the entity

People who participate in a study and from whom data is collected are typically called "subjects" or "participants". While "subject" has been standard in many sub-fields of cognitive sciences, "participant" has become more common recently and is considered more respectful to human study participants as it acknowledges their active involvement in the study. Other terms may be common in specific research domains investigating humans (e.g., "respondent", "patient", "child"), non-human animals (e.g., "primate", "mouse") or computational models (e.g., "agent"). Still, in other contexts, it might be customary to use more generic terms (e.g., "user"). Finally there are terms that are idiosyncratic to particular data collection services (e.g., "worker").

It is our view that the entity name in the data table should be generic to encompass a large set of use cases (e.g., children, animals, artificial agents) and we therefore second [BIDS](https://bids-specification.readthedocs.io/en/stable/) in the use of "subject" in the data specification and avoid using any other term in the data (however, contrary to BIDS we never use "participants"). This does not mean however that human participants should be addressed as "subjects" in general (for example, when communicating with them or about them); all participants are subjects, but not all subjects are participants (e.g., an AI-agent). Naming a column or data file using "subject" is convenient and does not imply disrespect towards human study participants.

> **Rule #2** **Use "subject" to refer to the entity generating the response data.** {: .rule }

## A suffix for the entity and format of the value

A reference to a subject can serve multiple purposes:

1.  Ensure the uniqueness of a subject within a study; link all data from a subject within a study.

2.  Select or identify data belonging to a particular subject. For example, if you see an outlier point in a plot and want to understand why that point occurred, it might be necessary to identify that data as belonging to a particular subject and then look in greater detail in that subject's data.

3.  Use the subject's identifier to name their data files.

4.  Ensure the uniqueness of a subject across studies. A subject may participate in multiple studies and it might be necessary (e.g., for meta-analyses) to determine whether subjects participated in multiple studies.

These four purposes have somewhat different requirements.

Purpose 1 requires uniqueness within a study while .4 requires uniqueness in general. For purpose 1 it would suffice to have a participant counter and assign an integer to each participant within a study. This leads to shorter names which makes it practical for purposes 2 and 3. To ensure the uniqueness of subject identifiers in general requires longer strings, which are rather impractical for data analysis and management.

Consequently, we adopt the following conventions:

subject_index

:   a string uniquely associated to each subject within a dataset. Following [BIDS](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#participant-names-and-other-labels), this string is obtained by concatenating the string `subject_` with a zero-padded number which "counts" subjects in a study (typically but not necessarily in chronological order). For example, the 15^th^ subject in a dataset might be assigned the subject_index value of subject_015.

Note that such zero-padding may depend on the number of subjects there are in a study (e.g., if there are less than 100, the first subject would be called "subject_01", but if there are more than 1000 subjects in total, that subject would be called "subject_0001"). By default, we use a zero-padded string of length 4 as this will be enough for the vast majority of behavioral datasets.

subject_id

:   a string that uniquely identifies a subject (typically within a data collection institution or research group) and may be used to determine if the same subject participated in multiple studies wherein they might be assigned different subject_index values. subject_id may be created using custom procedure and look something like: `20025fe6-6868-47c6-a222-a5c06b49c8db`.

Note that `subject_id` is not be present in the L1 data but instead is available in separate *Subjects* table which lists subject information, including their subject_index and subject_id values.