
### General

 nan

<br>accuracy	[float]
: `accuracy` refers to a measure of performance; in many tasks, it reflects the percentage (0-100%) or fraction (0-1) of correct responses. We will always use `accuracy` to refer to a performance measure that is a float and bounded in the [0-1] range.



correct	[boolean]
: `correct` is a boolean variable which indicates for a given trial or response whether it was correct or not. When no response was given when it should (i.e., timeout), correct evaluates to `FALSE` rather than `NA`. This is to avoid the case where people would be given a high performance score when in fact they avoided all difficult trials and responded correctly only to easy trials.




response_time	[float]
: the meaning of `response_time` (and its units) is not consistent across studies. For us, `response_time` is the duration between the moment the participant fully completed their response on a given trial and the moment that the earliest possible correct response could have been completed by an AI agent with perfect knowledge of the task and ability to instantaneously execute the response.
: **Default unit:** seconds 

:::{.callout-note}

 Other measures of durations exist and may be useful to describe a person's response. If such additional measures are needed, they should be specified explicitly. For example
 - `response_onset`
 - `response_offset`
 - `response_duration` 

:::


:::{.callout-note}

 Units for response times are not consistent across papers and publicly available datasets and one can find them expressed in either seconds or milliseconds. We decided to use seconds as the default unit for response times because:
 - avoid "exception" by always using seconds as duration measure.
 - avoid computation by keeping the units as they currently are in our raw data and task specs.
 - avoid the temptation to round rt to integers when expressed in milliseconds.
 - take advantage of the fact that most packages to analyse rt seem to be using seconds as a default unit; be congruent with what seems to be the default unit in fMRI measurements.  

:::


:::{.callout-note}

 It is tempting to abbreviate `response_time` as `rt`; however, there are several other variables prefixed `response_` which do not have abbreviations. Spelling the names out, while making the name longer, makes the overall data structure more consistent and explicit. 

:::



timed_out	[boolean]
: indicates whether the participant failed to respond within the allocated time period.



