

## Metadata

Metadata are data that provide information about a record, in our case, a dataset. Metadata can serve many functions, most important of which is to facilitate finding relevant datasets. There are numerous standards for such metadata. We use the standard defined by [schema.org](https://schema.org/Dataset), as this is a solid, industry standard that is both extensive and used by major dataset search engines (e.g., https://datasetsearch.research.google.com/). 
  
https://developers.google.com/search/docs/appearance/structured-data/dataset


We also recommend sharing data via [Zenodo](https://zenodo.org/) which a major platform for sharing scientific datasets. When uploading datasets, Zenodo offers an interface for describing the dataset which uses the fields defined by schema.org and generates metadata following that standard.



We also recommend adopting a minimal approach to the content of this metadata and to only fill out key information that may be useful for locating a particular dataset. More detailed information about the data (e.g., the codebook, the study protocol) may be included in the dataset itsels. Below we present the key properties to describe datasets within shema.org. For the offical full specification, see https://schema.org/Dataset.

### Required fields

| Property | Type | Description |
|---|---|---|
| name | Text | The name of the dataset. |
| description | Text | Description of the dataset. |
| license | URL | The license that applies to the dataset. |
| keywords | Text or URL | List of keywords or URLs delimited by commas. |
| creator | Organization or Person | The creator(s)/author(s) of the published dataset. |
| funding | Grant | A Grant that directly or indirectly provide funding or sponsorship for this item. |



url
datePublished
distribution
identifier
@id



### Recommended

| Property | Type | Description |
|---|---|---|
| creditText | Text | 	Text that can be used to credit person(s) and/or organization(s) associated with a published Creative Work. |
| version | Number or Text | The version of the dataset. |
| size | Text | The size of the dataset (e.g., 2.5GB). |
| maintainer | Person | Person that manages the datasets and should be contacted regarding any dataset related issues. |
| measurementMethod |  DefinedTerm, URL, Text | The type of method used to collect the data (e.g., "questionnaire", "computerize test", "video game".) |
| measurementTechnique | DefinedTerm, URL, Text | The instrument(s) used to collect the data (e.g., "Beck Depression Inventory") |
| variableMeasured | Property, PropertyValue, Text | Describes the type of construct being measured (e.g., "depression"), not the columns/variables in the dataset (e.g., "dep_q1"). | 








### Curated dataset

Sometimes a dataset is curated and shared by people who were not the original collectors of the dataset. In those cases it might be unclear how exactly to attribute proper credit to each type of contribution.

From our perspective, the creator(s) of a dataset are the people or organizations that published that specific version of the dataset, not the people or organisations that collected the data. If the shared dataset has been processed inadequatly, it would not make sense to blame to original data collectors for such mistakes.

This being said, the original data collectors must be appropriately credited. There are 5 mechanisms we recommend 

 - name of the dataset refers to original data creators;
 - description of the dataset states clearly that data collection was performed by other people;
 - citation provides a link to cite the original study
 - creditText provides credit to both the curated and the original versions
 - isBasedOn provides information and links to the original dataset.



A dataset is made availble in some form by 

Let's assume for exm
From our perspective, when a dataset is published, the creators of the dataset are those people who were responsible for 

metadata of that dataset should refer to that published version and the creators of that published version 



| Property | Type | Description |
|---|---|---|
| isBasedOn | URL or CreativeWork | A resource from which this work is derived or from which it is a modification or adaptation. |
| citation | CreativeWork or Text | A citation or reference to another creative work, such as another publication, web page, scholarly article, etc. |

