
## Dataset folder structure

<hr />


A dataset is a folder that contains data files and all relevant information needed to make sense of that data. The name of the folder is the name of the dataset. Here we describe the files and subfolders contained in a dataset folder.


::: {.callout title="General structure of a dataset"}

<br>
Dataset/<br>
├─ README.md<br>
├─ LICENSE<br>
├─ subjects/<br>
├─ study/<br>
├─ data/<br>
│  ├─ subject_001/<br>
│  ├─ subject_002/<br>
│  ├─ subject_*/<br>
├─ vignette/<br>
:::



### Dataset

The name of the dataset folder is the name of the dataset. To our knowledge there are no clear best practices for naming datasets. In general, we recommend the following rules:

- use a meaningful name (e.g., 'Income', 'CogntiveAssessment' rather than 'data').
- use project acronyms as they may be distinctive and unique (e.g., 'MNIST').
- append year of first data publication and other specifying information to disambiguate common names or designate subsets of larger datasets (e.g., 'IncomeLuxembourg2023').
- use CamelCase to name a dataset.
- When a dataset is linked to a publication, we recommend using the last name of the first author and the year of the publication to name the data (e.g., `Steyvers2019`). This is partiuclarly useful when curating, tidying and (re-)sharing past datasets as it makes the provenance and attribution of the data more explicit. 


We do not recommend to include the version in the dataset name but to have instead included in the metadata and to use a data version system.






### README.md

The README.md file contains the description and the metadata of the dataset. 

> What about a codebook?

Additional README.md files may exist at other locations within a dataset folder to cover more specific points. 




### LICENSE

The LICENSE file specifies the terms and conditions for use, reproduction and distribution of the dataset. While different licenses may apply to different parts of a dataset we recommend to keep it simple and to use the [CC-BY](https://creativecommons.org/licenses/by/4.0/) according to which the dataset may be used for any purpose as long as it is given appropriate credit. 



  


### subjects/

The subjects/ folder contains information about the subjects of the study. Typically, but not always, subjects will be study participants. This folder may for instance include a subjects.tsv table listing all participants in a study, demographic information as well as what data is available for each of them. This data is most useful for quickly locating specific data (e.g., where is the data for subjects that are male, aged 35 and who have completed at least 10 trials of a specific task?).

> include a subject_id that uniquely identifies a subjects within a datacollection.

### study/

The study/ folder contains information about the study. This includes in particular 
 - **instruments.tsv**: describes the instruments used for the data collection. 
 - **insructions.json**: describes the instructions presented to subjects.
 - **study_flow.json**: describes the flow of subjects across activities within a study.
 - other: for example, ethics approval and adminsitrative or technical documentation.


### data/

The data/ folder contains all the data collected within a study and that are within the scope of a dataset. Within data/ there is one folder per subject that contains all the data about that subject. 


### subject_*/
The subject data folder is labelled following the template `subject_{x}` where x refers to a zero-padded integer (e.g., `subject_001`, `subject_123`; the number of zeros used for padding should be commensurate with the number of subjects in the dataset. 

Additional folders may be included within each subjects' folder depending on the specific case. For example, there could be subfolders per session (e.g., `session_01`, `session_02`) and per data type (e.g., `questionnaire`, `behavior`, `fMRI`, `EEG`) and per instrument (e.g., `bisbas`, `stroop_test`). 








## Naming data files

We recommend using simple, short names for data files so they are easier to type and can be fully displayed on the screen. The location of a file provides context to a data file. For example `~/dataset/data/subject_001/session_1/Trial.tsv` is to preferred over  `~/dataset/data/subject_001/subject-001_session-1_Trial.tsv` as it is shorter and yet contains the same information.




## Data file types

### Tabular data

There are two main open file formats for storing tabular data:
- CSV (comma separated values)
- TSV (tab separated values)

CSV is more common but TSV is technically more efficient, less error prone and more human readable. TSV is in particular more appropriate than CSV in cases where the values in a cell can contain commas, which is obviously very common in text data, and where the commas within a cell must be distinguished from the commas that serve as separators (tabs are much less common in data values). Both TSV and CSV files can easily be important by most data analysis software. We therefor recommend using TSV for storing and sharing any tabular data. 


### Other

Other kinds of file types may be used to store non-tabular data. Markdown is a good choice for text documents and JSON or YAML may be appropriate for different kinds of structured data.




