---
order: 3
output-file: convert-your-dataset
title: Convert Your Dataset
subtitle: How to convert a behavior data table into a BDM dataset
---

Many experimental design tools outputs a single data table that contains all the data collected during a study. If this is the case and you want to convert this data file to BDM, follow the steps below.

## Prerequisites
- data file is CSV or any other format that can be read and manipulated.
- The data table contains all the necessary columns for BDM, including:
  - Subject ID
  - Task or questionnaire name
  - Observations (e.g., responses, ratings, etc.)
  - Any other relevant metadata, e.g., timestamps, conditions, etc.


## Dataset folder

- Create a new folder for your dataset.
- Create a `README.md` file in the main directory of the dataset folder.
- Create a `LICENSE` file in the main directory of the dataset folder.


## Data folder

- Split the data table into one table per activity per subject and save it in the corresponding subject's folder.
- Create a folder for each in the `agents/<agent_id>/<activity_id>/` folder add store that data in the `trials.csv` file.


## Studyflow
- Create a studyflow file. You can use the Studyflow Modeler to create a studyflow file. If you want to add subject-specific information (for example if they are assigned to different conditions), you can do this in the `studyflow.csv` file inside the subject's folder.

## Instruments
- Create an instrument file for each task/questionnaire in the `instruments/` folder. Each instrument file should contain the following information:
    - Name of the instrument
    - Description of the instrument
    - Any other relevant metadata, e.g., questions, parameters, etc.
