---
title: Naming responses and response options
---


Various terms and constructs are somehow related to the concept of a "response". Here we list those terms and clarify how we use them. To illustrate the various terms we will use the example of the digit span task where people have to click with their mouse on a virtual keyboard displayed on the screen which shows the digits 1 to 9, an "enter" button and a "delete" button.

input action

:   each time a subject clicks on a button, we record an (action) input of type "click". Input can be of different types (e.g., mouse-click, key-press). An input is not necessarily meaningful or interpreted.

input interface

:   The keyboard displayed on the screen is the input interface. The input interface can be of different types (e.g., buttons, text-field, slider).

response

:   is defined by the task and typically comprises only a subset of the inputs. For example, if the digit span task required reproducing a sequence of 3 digits (e.g, 3-5-7), the response might be 3-5-7 even though there might have been many more inputs (e.g., 3-6-delete-5-7-enter). Note that while "input" is an objective description of a type of event, "response" is an interpretation of a subset of those events that is tied to a specific the task definition. Sometimes people use "answer" or "choice" instead of "response". We use the generic term "response" in every case and may use other variables (e.g., "response_type") to qualify more specific types of responses (e.g., choice, number, text, choice-sequence).

option (i.e., response options)

:   in most computerized cognitive tests and surveys, subjects are offered a means to enter their response; most often this consists of a discrete set of options to choose from. This set is sometimes called "possible responses" or "answers"; we call this entity "option". It is important to record information about the response options because they directly determine the meaning of the data (e.g., a rating of "3" if very different if the scale goes from 1 to 3 versus 1 to 10).

:   One key concern when describing response options is how to name the "good" one. In the survey literature, that option is sometimes referred to as the "key" while the remaining options are called ["distractors"](https://images.pearsonassessments.com/images/tmrs/tmrs_rg/Distractor_Rationales.pdf). We will not use these terms because they are unfamiliar to most and may be confusing (as "distractor" could also refer to a stimulus role and a "key" could refer to a button on a keyboard or a column in a data table). It is also common to see the term "correct_response" (or equivalent) to designate the "good" option. `correct_response` is however ambiguous as it could refer to 1. the response that was given on a correct trial (i.e., correct serves as an adjective/filter); 2. what response will evaluate to correct (i.e., if `response == correct_response`, then `correct = TRUE`) or 3. a boolean indicating if the current response is correct or not (`is_response_correct`).

To refer to the option that we expect the subject to choose, we will use the term `expected_response`. If the actual response is equal to the expected response, the response is said to be "correct".

Note that responses can be evaluated and that several variables may be used to qualify this evaluation beyond the boolean `correct` variable. In particular, options (and thus responses) may be assigned a `score` (i.e., a numeric value that may reflect the meaning or value of an option), an `accuracy` (i.e., a float ranging from 0 to 1 reflecting the level of accuracy) and `evaluation_label` variables. Evaluation variables like `correct` are not a property of the option per se but depends on the "question" being asked; it is thus a property of the response as defined within a specific trial.