---
order: 4
output-file: studyflow
title: Studyflow
---

Studyflows are formal diagrams based on BPMN to describe cognitive research. They can be used to visually describe the study protocol, the analysis pipeline, or any other steps in a study. Studyflows facilitate communication with participants (e.g., automatically running a study), researchers (e.g., reproducible protocols and analyses), systems (e.g., automated data processing), and other stakeholders.

- [ ] TODO: Example diagrams

## Elements

Each Studyflow is a BPMN diagram with additional elements specific to cognitive research.

### Experimental design

The following elements can be used to describe the study protocol.

- [ ] `bpmn:StartEvent`: initiates the flow. There must be only one start event in a study.
- [ ] `bpmn:SequenceFlow`: connects the elements.
- [ ] `studyflow:Element`
    - [ ] `studyflow:Activity`: a generic task (`bpmn:Task`) that can be performed by a participant or a system.
        - [ ] `studyflow:CognitiveTest`: participant performs a cognitive test.
        - [ ] `studyflow:Questionnaire`: participant answers a questionnaire.
            - [ ] `studyflow:Consent`: participant provides consent for the study.
            - [ ] `studyflow:Instruction`: participant reads the instructions.
        - [ ] `studyflow:VideoGame`: participant plays a video game.
        - [ ] `studyflow:Rest`: participant takes a break, and performs no activity as in resting-state.
    - [ ] `studyflow:Dispatcher`: a subclass of `bpmn:ExclusiveGateway` that splits the flow into on of the multiple paths based on a condition.
        - [ ] `studyflow:RandomDispatcher`: a subclass of `Dispatcher` that randomly selects one of the outgoing paths.
- [ ] `bpmn:EndEvent` terminates the flow. There must be only one end event in a study.

### Modeling and data analysis

The following elements can be used to describe the analysis pipeline.

- `bpmn:StartEvent`: initiates the analysis pipeline. Unlike experimental design, there can be multiple start events in a pipeline.
- `bpmn:EndEvent`: terminates the analysis pipeline. Unlike experimental design, there can be multiple end events in a pipeline.
- [ ] TODO
